/*
 *  * Please do not edit this file.
 *   * It was generated using rpcgen.
 *    */

#ifndef _ACCOUNT_H_RPCGEN
#define _ACCOUNT_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif


#define ACCOUNT 0x20010929
#define ACCOUNT_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define deposit 2
    extern  int * deposit_1(int *, CLIENT *);
    extern  int * deposit_1_svc(int *, struct svc_req *);
#define withdraw 1
    extern  int * withdraw_1(int *, CLIENT *);
    extern  int * withdraw_1_svc(int *, struct svc_req *);
    extern int account_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define deposit 2
    extern  int * deposit_1();
    extern  int * deposit_1_svc();
#define withdraw 1
    extern  int * withdraw_1();
    extern  int * withdraw_1_svc();
    extern int account_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ACCOUNT_H_RPCGEN */

