/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"


void
testprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int int_echo_1_arg1;
	int  *result_2;
	char *get_str_len_1_arg1="Hello, world";
	int  *result_3;
	int add_1_arg1=10;
	int add_1_arg2=20;

#ifndef	DEBUG
	clnt = clnt_create (host, TESTPROG, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = int_echo_1(int_echo_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else  
        printf("[PRC1] echo %d, source %d\n", *result_1,  
               int_echo_1_arg1);
    
	result_2 = get_str_len_1(get_str_len_1_arg1, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else  
        printf("[RPC2] return %d, should %d\n", *result_2,  
               strlen(get_str_len_1_arg1));
    
	result_3 = add_1(add_1_arg1, add_1_arg2, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else  
        printf("[PRC3] %d+%d=%d\n", add_1_arg1, add_1_arg2,  
               *result_3);  
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	testprog_1 (host);
    exit (0);
}
