/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct add_1_argument {
	int arg1;
	int arg2;
};
typedef struct add_1_argument add_1_argument;

#define TESTPROG 30000
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define int_echo 1
extern  int * int_echo_1(int , CLIENT *);
extern  int * int_echo_1_svc(int , struct svc_req *);
#define get_str_len 2
extern  int * get_str_len_1(char *, CLIENT *);
extern  int * get_str_len_1_svc(char *, struct svc_req *);
#define add 3
extern  int * add_1(int , int , CLIENT *);
extern  int * add_1_svc(int , int , struct svc_req *);
extern int testprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define int_echo 1
extern  int * int_echo_1();
extern  int * int_echo_1_svc();
#define get_str_len 2
extern  int * get_str_len_1();
extern  int * get_str_len_1_svc();
#define add 3
extern  int * add_1();
extern  int * add_1_svc();
extern int testprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_add_1_argument (XDR *, add_1_argument*);

#else /* K&R C */
extern bool_t xdr_add_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
