/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"

int *
int_echo_1_svc(int arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
        //echo.  
    result=arg1;  
    printf("[RPC1] source=%d, echo=%d\n", arg1, result);
    
	return &result;
}

int *
get_str_len_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
            //get strlen.  
     result=strlen(arg1);  
     printf("[PRC2] str=%s, len=%d\n", arg1, result);
        
     return &result;
}

int *
add_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
     result=arg1+arg2;  
     printf("[RPC3] %d+%d=%d\n", arg1, arg2, result);
     
	return &result;
}
